
package com.televisa.comer.integration.secman.grupos;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SecmanDasUsuariosGrupoService",
                  targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                  wsdlLocation =
                  "http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasUsuariosGrupoPort?wsdl#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasUsuariosGrupoService")
public class SecmanDasUsuariosGrupoService extends Service {

    private final static URL SECMANDASUSUARIOSGRUPOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECMANDASUSUARIOSGRUPOSERVICE_EXCEPTION;
    private final static QName SECMANDASUSUARIOSGRUPOSERVICE_QNAME =
        new QName("http://webServices.view.secman.televisa.com.mx/", "SecmanDasUsuariosGrupoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://tvmiddev1.televisa.net:10106/SecmanWebServices/SecmanDasUsuariosGrupoPort?wsdl#%7Bhttp%3A%2F%2FwebServices.view.secman.televisa.com.mx%2F%7DSecmanDasUsuariosGrupoService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECMANDASUSUARIOSGRUPOSERVICE_WSDL_LOCATION = url;
        SECMANDASUSUARIOSGRUPOSERVICE_EXCEPTION = e;
    }

    public SecmanDasUsuariosGrupoService() {
        super(__getWsdlLocation(), SECMANDASUSUARIOSGRUPOSERVICE_QNAME);
    }

    public SecmanDasUsuariosGrupoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECMANDASUSUARIOSGRUPOSERVICE_QNAME, features);
    }

    public SecmanDasUsuariosGrupoService(URL wsdlLocation) {
        super(wsdlLocation, SECMANDASUSUARIOSGRUPOSERVICE_QNAME);
    }

    public SecmanDasUsuariosGrupoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECMANDASUSUARIOSGRUPOSERVICE_QNAME, features);
    }

    public SecmanDasUsuariosGrupoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecmanDasUsuariosGrupoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SecmanDasUsuariosGrupo
     */
    @WebEndpoint(name = "SecmanDasUsuariosGrupoPort")
    public SecmanDasUsuariosGrupo getSecmanDasUsuariosGrupoPort() {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/", "SecmanDasUsuariosGrupoPort"),
                             SecmanDasUsuariosGrupo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecmanDasUsuariosGrupo
     */
    @WebEndpoint(name = "SecmanDasUsuariosGrupoPort")
    public SecmanDasUsuariosGrupo getSecmanDasUsuariosGrupoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.view.secman.televisa.com.mx/", "SecmanDasUsuariosGrupoPort"),
                             SecmanDasUsuariosGrupo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECMANDASUSUARIOSGRUPOSERVICE_EXCEPTION != null) {
            throw SECMANDASUSUARIOSGRUPOSERVICE_EXCEPTION;
        }
        return SECMANDASUSUARIOSGRUPOSERVICE_WSDL_LOCATION;
    }

}
