
package com.televisa.comer.integration.secman.grupos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.televisa.comer.integration.secman.grupos.types.ObjectFactory;
import com.televisa.comer.integration.secman.grupos.types.UsuariosCollection;
import com.televisa.comer.integration.secman.grupos.types.UsuariosGrupoInputParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SecmanDasUsuariosGrupo", targetNamespace = "http://webServices.view.secman.televisa.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SecmanDasUsuariosGrupo {


    /**
     *
     * @param arg0
     * @return
     *     returns com.televisa.comer.integration.secman.grupos.types.UsuariosCollection
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuariosGrupo",
                    targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                    className = "com.televisa.comer.integration.secman.grupos.types.ObtenerUsuariosGrupo")
    @ResponseWrapper(localName = "obtenerUsuariosGrupoResponse",
                     targetNamespace = "http://webServices.view.secman.televisa.com.mx/",
                     className = "com.televisa.comer.integration.secman.grupos.types.ObtenerUsuariosGrupoResponse")
    public UsuariosCollection obtenerUsuariosGrupo(@WebParam(name = "arg0", targetNamespace = "")
                                                   UsuariosGrupoInputParameters arg0);

}
