package com.televisa.comer.integration.secman.email;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class SecmanDasEnviarCorreoSoap12HttpPortClient {
    public static void main(String[] args) {
        SecmanDasEnviarCorreo_Service secmanDasEnviarCorreo_Service = new SecmanDasEnviarCorreo_Service();
        SecmanDasEnviarCorreo secmanDasEnviarCorreo =
            secmanDasEnviarCorreo_Service.getSecmanDasEnviarCorreoSoap12HttpPort();
        // Add your code to call the desired methods.


    }
}
